const BUTTON_COLOR_SELECTED="#FEBC5F";
const BUTTON_COLOR="#DBDBDB";
const MAIN_COLOR="#A7050E";
const MAIN_MARGIN_RIGHT=24;
const MAIN_MARGIN_LEFT=24;
const MAIN_MARGIN_TOP="5%";

export const VAR={
    BUTTON_COLOR_SELECTED:BUTTON_COLOR_SELECTED,
    BUTTON_COLOR:BUTTON_COLOR,
    MAIN_COLOR:MAIN_COLOR,
    MAIN_MARGIN_RIGHT:MAIN_MARGIN_RIGHT,
    MAIN_MARGIN_LEFT:MAIN_MARGIN_LEFT,
    MAIN_MARGIN_TOP:MAIN_MARGIN_TOP
}